### PR TITLE
ci: test Node.js 6, 8, 10 and 11

### PR DESCRIPTION
**Pull request by DanielRuf**
Current LTS are 6, 8 and 10 and we should test there too to catch any issues and check if Node.js 6 users can still use this library.

### CODE REVIEW

**Comment by DanielRuf** [comment]
Then let's make this clear in `engines.node` in package.json.

**Comment by DanielRuf** [comment]
Also still failing: https://github.com/xxczaki/cash-cli/commits/master

**Comment by xxczaki** [comment]
@DanielRuf Looks like it's working now :smile: However, tests are now much less stricter, because users now need to provide their own https://fixer.io API key :cry: I don't know how we can test the actual conversion without hardcoding the API key :/

**Comment by DanielRuf** [comment]
> @DanielRuf Looks like it's working now 😄 However, tests are now much less strict because users now need to provide their own [fixer.io](https://fixer.io) API key 😢 I don't know how we can test the actual conversion without hardcoding the API key :/

Is there something like tokens for such cases or just one API key for everything?

**Comment by xxczaki** [comment]
@DanielRuf I think API key is used for everything, according to fixer.io documentation :/ Year ago, fixer.io used to be a free service, without tokens or API keys, but it was acquired by apilayer. I was using my personal key for this app, but a few days ago the requests limit (1000) has been exceeded :cry:

**Comment by xxczaki** [comment]
@DanielRuf Just published version 3.0. Thanks for this pull request :unicorn:

**Pull request merged**
